### PR TITLE
Generate ds file

### PR DESCRIPTION
**Pull request by hudecof**
added DS file genereation code for #5 .

In the parent zone, if is handed by the same server you could use `$INCLUDE` statement.

For corrent signing, the wrapper for `ldns-signzone` needs to be used.

### CODE REVIEW

**Comment by hudecof** [comment]
@northox seems, that tehre are both (also #6) patches included ;( I merged the #6 into my master allready.

**Comment by northox** [comment]
Thanks! I'll test this out today or tomorrow.

**Comment by hudecof** [comment]
tehre are no test cases, but it should work, at least im my lab it's working

**Comment by northox** [comment]
Sorry for the delay and thanks!

**Pull request merged**
